### ISSUE TITLE
Support Grappelli 2.7.2

### ISSUE THREAD

**Issue by olivierdalang** [CrossWaterBridge/django-grappelli-autocomplete-fk-edit-link#1]
Hi,

I'd love to use this, but from what I read in `setup.py`, it is not compatible with the latest version of grappelli :

```
install_requires=[
        'django-grappelli==2.6.3',
    ]
```

I'd love to help but am only beginning with Django... I'll still look at the code to see if I manage to make a PR !

Thanks !

**Comment by hiltonc** [comment]
Fixed! Let me know if you have any problems with it.

**Comment by olivierdalang** [comment]
Hi,

Wow, that was fast !!

Still it doesn't work here, after following instructions, I get a 404 error on `http://127.0.0.1:8000/static/admin/js/autocomplete-fk-edit-link.js`.
The file is not in /static/, even after collectstatic.
I tried to copy it from the repository to the right place in static, but oddly, it doesn't work.
All other statics are loaded correctly.

Not sure if it's my fault (as said, I'm rather new to Django).

**Comment by hiltonc** [comment]
I'm not sure what could be broken. I have this in my config:

```
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
)
```

Could that be a difference?

If not, do you have a small project with the problem that you could send me? I'd be happy to try to get it to work.

**Comment by olivierdalang** [comment]
Thanks a lot !

Here's a very small project : https://www.dropbox.com/s/zmixqlne9hb5i4k/TestingProject.zip?dl=0

You can just unzip, run collectstatic and runserver, I already created a superuser: admin // 1234

On `http://127.0.0.1:8000/admin/TestingApp/basemodel/1/`, I get the 404 error, and nothing collected in the static folder.

The STATICFILES_FINDERS lines didn't change anything.

**Comment by hiltonc** [comment]
Thanks, that helped me figure it out. I had the packaging wrong for the app. If you upgrade the app it should work for you now. Sorry about that!

**Comment by olivierdalang** [comment]
Cool, I'll test and let you know ! Thanks so much for the great work and the awesome support !

**Comment by olivierdalang** [comment]
Ok, I tested a bit, and the edit link appears correctly !

I don't know how it worked under previous grappelli versions, but I see issues still (I can open an issue for each of those if you prefer):
- (major) it doesn't open in a popup, so it discards the current form
- (minor) I'm not sure how styling is expected, but here it appears in a new line, not on the right of the widget like for normal foreign key widgets (see image)
- (feature) Once stable, will you submit it to PyPI ?

![screenshot](https://cloud.githubusercontent.com/assets/1894106/10182691/90112822-6716-11e5-9652-3f999fee93d6.png)

(note : in the zip, I did forget to add  'grappelli_autocomplete_fk_edit_link' in settings, hehe :) still, I the collectstatic bug was there and is fixed !)

EDIT : I opened those as separate issues
